# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1200, 803)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../source/timg.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        main.setToolTip("")
        main.setStyleSheet("font: 9pt \"楷体\";\n"
"background-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 0, 0);\n"
"font: 12pt \"黑体\";\n"
"selection-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"selection-color: rgb(255, 0, 0);")
        main.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.label_user_hospital = QtWidgets.QLabel(self.centralwidget)
        self.label_user_hospital.setGeometry(QtCore.QRect(170, 70, 211, 41))
        self.label_user_hospital.setStyleSheet("font: 12pt \"Agency FB\";\n"
"background-color: rgba(46, 187, 150, 125);")
        self.label_user_hospital.setObjectName("label_user_hospital")
        self.label_user_name = QtWidgets.QLabel(self.centralwidget)
        self.label_user_name.setGeometry(QtCore.QRect(170, 20, 71, 41))
        self.label_user_name.setStyleSheet("font: 12pt \"Agency FB\";\n"
"background-color: rgba(46, 187, 150, 125);")
        self.label_user_name.setObjectName("label_user_name")
        self.label_datetime = QtWidgets.QLabel(self.centralwidget)
        self.label_datetime.setGeometry(QtCore.QRect(400, 70, 231, 41))
        self.label_datetime.setStyleSheet("font: 14pt \"仿宋\";\n"
"background-color: rgba(46, 187, 150, 125);")
        self.label_datetime.setObjectName("label_datetime")
        self.label_head = QtWidgets.QLabel(self.centralwidget)
        self.label_head.setGeometry(QtCore.QRect(40, 20, 90, 90))
        self.label_head.setText("")
        self.label_head.setPixmap(QtGui.QPixmap("../../../../../myself/项目/朱总(北京同明眼科)/png/head.png"))
        self.label_head.setObjectName("label_head")
        self.label_user_title = QtWidgets.QLabel(self.centralwidget)
        self.label_user_title.setGeometry(QtCore.QRect(280, 20, 101, 41))
        self.label_user_title.setStyleSheet("font: 12pt \"Agency FB\";\n"
"background-color: rgba(46, 187, 150, 125);")
        self.label_user_title.setObjectName("label_user_title")
        self.label_weekday = QtWidgets.QLabel(self.centralwidget)
        self.label_weekday.setGeometry(QtCore.QRect(400, 20, 231, 41))
        self.label_weekday.setStyleSheet("font: 14pt \"仿宋\";\n"
"background-color: rgba(46, 187, 150, 125);")
        self.label_weekday.setAlignment(QtCore.Qt.AlignCenter)
        self.label_weekday.setObjectName("label_weekday")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 130, 1211, 671))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 671))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("selection-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
"font: 16pt \"Agency FB\";")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(10, 41, 1201, 591))
        self.tableView.setObjectName("tableView")
        self.lineEdit_search = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_search.setGeometry(QtCore.QRect(890, 0, 211, 41))
        self.lineEdit_search.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lineEdit_search.setStyleSheet("border-color: rgb(0, 85, 255);\n"
"font: 9pt \"Agency FB\";\n"
"border-color: rgb(30, 192, 255);")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.btn_search = QtWidgets.QPushButton(self.tab)
        self.btn_search.setGeometry(QtCore.QRect(1100, 0, 101, 41))
        self.btn_search.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.btn_search.setObjectName("btn_search")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 40, 191, 141))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 40, 191, 141))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 40, 191, 141))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(920, 40, 191, 141))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 230, 191, 141))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(370, 230, 191, 141))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(650, 230, 191, 141))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(920, 230, 191, 141))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 430, 191, 141))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(370, 430, 191, 141))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableView_2 = QtWidgets.QTableView(self.tab_3)
        self.tableView_2.setGeometry(QtCore.QRect(10, 40, 1201, 591))
        self.tableView_2.setObjectName("tableView_2")
        self.btn_search_2 = QtWidgets.QPushButton(self.tab_3)
        self.btn_search_2.setGeometry(QtCore.QRect(1110, 0, 101, 41))
        self.btn_search_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.btn_search_2.setObjectName("btn_search_2")
        self.lineEdit_search_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_search_2.setGeometry(QtCore.QRect(900, 0, 211, 41))
        self.lineEdit_search_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lineEdit_search_2.setStyleSheet("border-color: rgb(0, 85, 255);\n"
"font: 9pt \"Agency FB\";\n"
"border-color: rgb(30, 192, 255);")
        self.lineEdit_search_2.setObjectName("lineEdit_search_2")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_23.setGeometry(QtCore.QRect(90, 80, 191, 141))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_24.setGeometry(QtCore.QRect(640, 80, 191, 141))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_25.setGeometry(QtCore.QRect(360, 80, 191, 141))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_26.setGeometry(QtCore.QRect(910, 80, 191, 141))
        self.pushButton_26.setObjectName("pushButton_26")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_head_2 = QtWidgets.QLabel(self.tab_4)
        self.label_head_2.setGeometry(QtCore.QRect(190, 150, 191, 201))
        self.label_head_2.setText("")
        self.label_head_2.setPixmap(QtGui.QPixmap("../../../../../myself/项目/朱总(北京同明眼科)/png/statistics.png"))
        self.label_head_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_head_2.setObjectName("label_head_2")
        self.label_head_3 = QtWidgets.QLabel(self.tab_4)
        self.label_head_3.setGeometry(QtCore.QRect(490, 150, 191, 201))
        self.label_head_3.setText("")
        self.label_head_3.setPixmap(QtGui.QPixmap("../../../../../myself/项目/朱总(北京同明眼科)/png/statistics.png"))
        self.label_head_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_head_3.setObjectName("label_head_3")
        self.label_head_4 = QtWidgets.QLabel(self.tab_4)
        self.label_head_4.setGeometry(QtCore.QRect(810, 150, 191, 201))
        self.label_head_4.setText("")
        self.label_head_4.setPixmap(QtGui.QPixmap("../../../../../myself/项目/朱总(北京同明眼科)/png/statistics.png"))
        self.label_head_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_head_4.setObjectName("label_head_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 1201, 131))
        self.pushButton.setStyleSheet("background-color: rgb(46, 187, 150);\n"
"border-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 0);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.raise_()
        self.label_user_hospital.raise_()
        self.label_user_name.raise_()
        self.label_datetime.raise_()
        self.label_head.raise_()
        self.label_user_title.raise_()
        self.label_weekday.raise_()
        self.tabWidget.raise_()
        main.setCentralWidget(self.centralwidget)

        self.retranslateUi(main)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "北京同明眼科专家"))
        self.label_user_hospital.setText(_translate("main", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">北京大学第三人民医院</span></p></body></html>"))
        self.label_user_name.setText(_translate("main", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">杨雷</span></p></body></html>"))
        self.label_datetime.setText(_translate("main", "<html><head/><body><p><span style=\" color:#ffffff;\">08:08:56 2017-11-23</span></p></body></html>"))
        self.label_user_title.setText(_translate("main", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">主任医师</span></p></body></html>"))
        self.label_weekday.setText(_translate("main", "<html><head/><body><p>星期一</p></body></html>"))
        self.btn_search.setText(_translate("main", "搜  索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("main", "待诊"))
        self.pushButton_3.setText(_translate("main", "新生儿（3--7天）眼保健情况记录"))
        self.pushButton_4.setText(_translate("main", "42天眼保健情况记录"))
        self.pushButton_5.setText(_translate("main", "5--6个月眼保健情况记录"))
        self.pushButton_6.setText(_translate("main", "1岁儿童眼保健情况记录"))
        self.pushButton_7.setText(_translate("main", "2岁儿童眼保健情况记录"))
        self.pushButton_8.setText(_translate("main", "3岁儿童眼保健情况记录"))
        self.pushButton_9.setText(_translate("main", "3岁儿童眼保健情况记录"))
        self.pushButton_10.setText(_translate("main", "4岁儿童眼保健情况记录"))
        self.pushButton_11.setText(_translate("main", "5岁儿童眼保健情况记录"))
        self.pushButton_12.setText(_translate("main", "6岁儿童眼保健情况记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("main", "工作台"))
        self.btn_search_2.setText(_translate("main", "搜  索"))
        self.pushButton_23.setText(_translate("main", "杨同学"))
        self.pushButton_24.setText(_translate("main", "张同学"))
        self.pushButton_25.setText(_translate("main", "刘同学"))
        self.pushButton_26.setText(_translate("main", "李同学"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("main", "档案馆"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("main", "统计"))

