# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1190, 803)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/doctor_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        main.setToolTip("")
        main.setStyleSheet("font: 9pt \"楷体\";\n"
"background-color: rgb(245, 245, 245);\n"
"gridline-color: rgb(255, 0, 0);\n"
"font: 12pt \"黑体\";\n"
"selection-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"selection-color: rgb(255, 0, 0);")
        main.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.label_user_hospital = QtWidgets.QLabel(self.centralwidget)
        self.label_user_hospital.setGeometry(QtCore.QRect(0, 0, 241, 41))
        self.label_user_hospital.setStyleSheet("font: 16pt \"新宋体\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_user_hospital.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_hospital.setObjectName("label_user_hospital")
        self.label_user_name = QtWidgets.QLabel(self.centralwidget)
        self.label_user_name.setGeometry(QtCore.QRect(250, 0, 201, 41))
        self.label_user_name.setStyleSheet("font: 16pt \"新宋体\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_name.setObjectName("label_user_name")
        self.label_datetime = QtWidgets.QLabel(self.centralwidget)
        self.label_datetime.setGeometry(QtCore.QRect(780, 0, 231, 41))
        self.label_datetime.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_datetime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_datetime.setObjectName("label_datetime")
        self.label_user_title = QtWidgets.QLabel(self.centralwidget)
        self.label_user_title.setGeometry(QtCore.QRect(470, 0, 181, 41))
        self.label_user_title.setStyleSheet("font: 16pt \"新宋体\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_user_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_title.setObjectName("label_user_title")
        self.label_weekday = QtWidgets.QLabel(self.centralwidget)
        self.label_weekday.setGeometry(QtCore.QRect(1020, 0, 81, 41))
        self.label_weekday.setStyleSheet("font: 16pt \"新宋体\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 85, 255);")
        self.label_weekday.setAlignment(QtCore.Qt.AlignCenter)
        self.label_weekday.setObjectName("label_weekday")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setGeometry(QtCore.QRect(0, 42, 1192, 761))
        self.tabWidget_main.setMinimumSize(QtCore.QSize(0, 671))
        self.tabWidget_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_main.setStyleSheet("alternate-background-color: rgb(245, 245, 245);\n"
"font: 16pt \"新宋体\";\n"
"selection-color: rgb(245, 245, 245);\n"
"background-color: rgb(245, 245, 245);\n"
"selection-background-color: rgb(245, 245, 245);")
        self.tabWidget_main.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_main.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_main.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget_main.setTabBarAutoHide(False)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_uncheck = QtWidgets.QWidget()
        self.tab_uncheck.setObjectName("tab_uncheck")
        self.tableWidget_uncheck = QtWidgets.QTableWidget(self.tab_uncheck)
        self.tableWidget_uncheck.setGeometry(QtCore.QRect(-1, 41, 1187, 661))
        self.tableWidget_uncheck.setStyleSheet("gridline-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 255);\n"
"background-color: rgb(245, 245, 245);")
        self.tableWidget_uncheck.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_uncheck.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_uncheck.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_uncheck.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_uncheck.setRowCount(0)
        self.tableWidget_uncheck.setColumnCount(0)
        self.tableWidget_uncheck.setObjectName("tableWidget_uncheck")
        self.lineEdit_uncheck_search = QtWidgets.QLineEdit(self.tab_uncheck)
        self.lineEdit_uncheck_search.setGeometry(QtCore.QRect(739, 0, 211, 41))
        self.lineEdit_uncheck_search.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lineEdit_uncheck_search.setStyleSheet("border-color: rgb(0, 85, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"华文楷体\";\n"
"border-color: rgb(30, 192, 255);")
        self.lineEdit_uncheck_search.setObjectName("lineEdit_uncheck_search")
        self.btn_uncheck_search = QtWidgets.QPushButton(self.tab_uncheck)
        self.btn_uncheck_search.setGeometry(QtCore.QRect(950, 0, 91, 41))
        self.btn_uncheck_search.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 245, 245);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/mouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_uncheck_search.setIcon(icon1)
        self.btn_uncheck_search.setObjectName("btn_uncheck_search")
        self.btn_uncheck_update = QtWidgets.QPushButton(self.tab_uncheck)
        self.btn_uncheck_update.setGeometry(QtCore.QRect(1045, 0, 141, 41))
        self.btn_uncheck_update.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 245, 245);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/source/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_uncheck_update.setIcon(icon2)
        self.btn_uncheck_update.setObjectName("btn_uncheck_update")
        self.labe_update_info1 = QtWidgets.QLabel(self.tab_uncheck)
        self.labe_update_info1.setGeometry(QtCore.QRect(330, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labe_update_info1.setFont(font)
        self.labe_update_info1.setStyleSheet("font: 16pt \"华文楷体\";")
        self.labe_update_info1.setAlignment(QtCore.Qt.AlignCenter)
        self.labe_update_info1.setObjectName("labe_update_info1")
        self.labe_update_info_count = QtWidgets.QLabel(self.tab_uncheck)
        self.labe_update_info_count.setGeometry(QtCore.QRect(360, 10, 51, 21))
        self.labe_update_info_count.setStyleSheet("font: 16pt \"华文楷体\";\n"
"color: rgb(255, 0, 0);")
        self.labe_update_info_count.setAlignment(QtCore.Qt.AlignCenter)
        self.labe_update_info_count.setObjectName("labe_update_info_count")
        self.labe_update_info1_3 = QtWidgets.QLabel(self.tab_uncheck)
        self.labe_update_info1_3.setGeometry(QtCore.QRect(410, 10, 81, 21))
        self.labe_update_info1_3.setStyleSheet("font: 16pt \"华文楷体\";")
        self.labe_update_info1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labe_update_info1_3.setObjectName("labe_update_info1_3")
        self.btn_appoint_new = QtWidgets.QPushButton(self.tab_uncheck)
        self.btn_appoint_new.setGeometry(QtCore.QRect(0, 0, 91, 41))
        self.btn_appoint_new.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 245, 245);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/source/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_appoint_new.setIcon(icon3)
        self.btn_appoint_new.setObjectName("btn_appoint_new")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/source/computer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_main.addTab(self.tab_uncheck, icon4, "")
        self.tab_workbench = QtWidgets.QWidget()
        self.tab_workbench.setObjectName("tab_workbench")
        self.pushButton_42 = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_42.setGeometry(QtCore.QRect(520, 60, 121, 121))
        self.pushButton_42.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/2.png);")
        self.pushButton_42.setText("")
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_newborn = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_newborn.setGeometry(QtCore.QRect(280, 60, 121, 121))
        self.pushButton_newborn.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/1.png);")
        self.pushButton_newborn.setText("")
        self.pushButton_newborn.setAutoDefault(True)
        self.pushButton_newborn.setDefault(False)
        self.pushButton_newborn.setFlat(False)
        self.pushButton_newborn.setObjectName("pushButton_newborn")
        self.pushButton_56 = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_56.setGeometry(QtCore.QRect(770, 60, 121, 121))
        self.pushButton_56.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/3.png);")
        self.pushButton_56.setText("")
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_3y = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_3y.setGeometry(QtCore.QRect(770, 260, 121, 121))
        self.pushButton_3y.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/6.png);")
        self.pushButton_3y.setText("")
        self.pushButton_3y.setObjectName("pushButton_3y")
        self.pushButton_2y = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_2y.setGeometry(QtCore.QRect(520, 260, 121, 121))
        self.pushButton_2y.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/5.png);")
        self.pushButton_2y.setText("")
        self.pushButton_2y.setObjectName("pushButton_2y")
        self.pushButton_1y = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_1y.setGeometry(QtCore.QRect(280, 260, 121, 121))
        self.pushButton_1y.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/4.png);")
        self.pushButton_1y.setText("")
        self.pushButton_1y.setObjectName("pushButton_1y")
        self.pushButton_6y = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_6y.setGeometry(QtCore.QRect(770, 460, 121, 121))
        self.pushButton_6y.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/9.png);")
        self.pushButton_6y.setText("")
        self.pushButton_6y.setObjectName("pushButton_6y")
        self.pushButton_4y = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_4y.setGeometry(QtCore.QRect(280, 460, 121, 121))
        self.pushButton_4y.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/7.png);")
        self.pushButton_4y.setText("")
        self.pushButton_4y.setObjectName("pushButton_4y")
        self.pushButton_5y = QtWidgets.QPushButton(self.tab_workbench)
        self.pushButton_5y.setGeometry(QtCore.QRect(520, 460, 121, 121))
        self.pushButton_5y.setStyleSheet("background-color: rgba(245, 245, 245, 245);\n"
"image: url(:/source/8.png);")
        self.pushButton_5y.setText("")
        self.pushButton_5y.setObjectName("pushButton_5y")
        self.line = QtWidgets.QFrame(self.tab_workbench)
        self.line.setGeometry(QtCore.QRect(230, 220, 711, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_workbench)
        self.line_2.setGeometry(QtCore.QRect(230, 420, 711, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(self.tab_workbench)
        self.label_8.setGeometry(QtCore.QRect(280, 190, 121, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_workbench)
        self.label_9.setGeometry(QtCore.QRect(520, 190, 121, 31))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_workbench)
        self.label_10.setGeometry(QtCore.QRect(770, 190, 121, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_workbench)
        self.label_11.setGeometry(QtCore.QRect(280, 390, 121, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_workbench)
        self.label_12.setGeometry(QtCore.QRect(520, 390, 121, 31))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_workbench)
        self.label_13.setGeometry(QtCore.QRect(770, 390, 121, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_workbench)
        self.label_14.setGeometry(QtCore.QRect(770, 590, 121, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_workbench)
        self.label_15.setGeometry(QtCore.QRect(520, 590, 121, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_workbench)
        self.label_16.setGeometry(QtCore.QRect(280, 590, 121, 31))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.pushButton_42.raise_()
        self.pushButton_newborn.raise_()
        self.pushButton_56.raise_()
        self.pushButton_3y.raise_()
        self.pushButton_2y.raise_()
        self.pushButton_1y.raise_()
        self.pushButton_6y.raise_()
        self.pushButton_4y.raise_()
        self.pushButton_5y.raise_()
        self.line.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.line_2.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/source/laptop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_main.addTab(self.tab_workbench, icon5, "")
        self.tab_archives = QtWidgets.QWidget()
        self.tab_archives.setObjectName("tab_archives")
        self.comboBox_item_checked = QtWidgets.QComboBox(self.tab_archives)
        self.comboBox_item_checked.setGeometry(QtCore.QRect(-1, 2, 161, 37))
        self.comboBox_item_checked.setStyleSheet("selection-color: rgb(0, 0, 255);")
        self.comboBox_item_checked.setObjectName("comboBox_item_checked")
        self.dateEdit_end_checked = QtWidgets.QDateEdit(self.tab_archives)
        self.dateEdit_end_checked.setGeometry(QtCore.QRect(380, 2, 170, 35))
        self.dateEdit_end_checked.setStyleSheet("font: 20pt \"Adobe Arabic\";\n"
"color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.dateEdit_end_checked.setCalendarPopup(True)
        self.dateEdit_end_checked.setObjectName("dateEdit_end_checked")
        self.label_statistics_count_checked = QtWidgets.QLabel(self.tab_archives)
        self.label_statistics_count_checked.setGeometry(QtCore.QRect(700, 2, 71, 31))
        self.label_statistics_count_checked.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_statistics_count_checked.setAlignment(QtCore.Qt.AlignCenter)
        self.label_statistics_count_checked.setObjectName("label_statistics_count_checked")
        self.dateEdit_start_checked = QtWidgets.QDateEdit(self.tab_archives)
        self.dateEdit_start_checked.setGeometry(QtCore.QRect(170, 2, 170, 35))
        self.dateEdit_start_checked.setStyleSheet("font: 20pt \"Adobe Arabic\";\n"
"color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.dateEdit_start_checked.setCalendarPopup(True)
        self.dateEdit_start_checked.setObjectName("dateEdit_start_checked")
        self.label_3 = QtWidgets.QLabel(self.tab_archives)
        self.label_3.setGeometry(QtCore.QRect(660, 2, 41, 31))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab_archives)
        self.label_5.setGeometry(QtCore.QRect(780, 2, 31, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_archives)
        self.label_6.setGeometry(QtCore.QRect(345, 2, 31, 31))
        self.label_6.setObjectName("label_6")
        self.btn_children_query = QtWidgets.QPushButton(self.tab_archives)
        self.btn_children_query.setGeometry(QtCore.QRect(560, 0, 91, 41))
        self.btn_children_query.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.btn_children_query.setIcon(icon1)
        self.btn_children_query.setObjectName("btn_children_query")
        self.tableWidget_children_manage = QtWidgets.QTableWidget(self.tab_archives)
        self.tableWidget_children_manage.setGeometry(QtCore.QRect(0, 40, 1191, 671))
        self.tableWidget_children_manage.setStyleSheet("gridline-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 255);\n"
"background-color: rgb(245, 245, 245);")
        self.tableWidget_children_manage.setObjectName("tableWidget_children_manage")
        self.tableWidget_children_manage.setColumnCount(0)
        self.tableWidget_children_manage.setRowCount(0)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/source/user_check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_main.addTab(self.tab_archives, icon6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(1040, 1, 41, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(1150, 1, 31, 31))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(720, 1, 31, 31))
        self.label_19.setObjectName("label_19")
        self.btn_stat_query = QtWidgets.QPushButton(self.tab)
        self.btn_stat_query.setGeometry(QtCore.QRect(940, -1, 91, 39))
        self.btn_stat_query.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.btn_stat_query.setIcon(icon1)
        self.btn_stat_query.setObjectName("btn_stat_query")
        self.comboBox_stat_item = QtWidgets.QComboBox(self.tab)
        self.comboBox_stat_item.setGeometry(QtCore.QRect(390, 0, 161, 35))
        self.comboBox_stat_item.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.comboBox_stat_item.setObjectName("comboBox_stat_item")
        self.dateEdit_stat_start = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_stat_start.setGeometry(QtCore.QRect(550, 1, 161, 35))
        self.dateEdit_stat_start.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);\n"
"font: 20pt \"Adobe Arabic\";")
        self.dateEdit_stat_start.setCalendarPopup(True)
        self.dateEdit_stat_start.setObjectName("dateEdit_stat_start")
        self.comboBox_stat_doctor = QtWidgets.QComboBox(self.tab)
        self.comboBox_stat_doctor.setGeometry(QtCore.QRect(270, 0, 121, 35))
        self.comboBox_stat_doctor.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.comboBox_stat_doctor.setObjectName("comboBox_stat_doctor")
        self.tableWidget_stat = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_stat.setGeometry(QtCore.QRect(0, 40, 1191, 671))
        self.tableWidget_stat.setStyleSheet("gridline-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 255);\n"
"background-color: rgb(245, 245, 245);")
        self.tableWidget_stat.setObjectName("tableWidget_stat")
        self.tableWidget_stat.setColumnCount(0)
        self.tableWidget_stat.setRowCount(0)
        self.label_statistics_count = QtWidgets.QLabel(self.tab)
        self.label_statistics_count.setGeometry(QtCore.QRect(1070, 1, 71, 31))
        self.label_statistics_count.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_statistics_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_statistics_count.setObjectName("label_statistics_count")
        self.dateEdit_stat_end = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_stat_end.setGeometry(QtCore.QRect(758, 1, 181, 35))
        self.dateEdit_stat_end.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);\n"
"font: 20pt \"Adobe Arabic\";")
        self.dateEdit_stat_end.setCalendarPopup(True)
        self.dateEdit_stat_end.setObjectName("dateEdit_stat_end")
        self.comboBox_stat_hospital = QtWidgets.QComboBox(self.tab)
        self.comboBox_stat_hospital.setGeometry(QtCore.QRect(0, 0, 271, 35))
        self.comboBox_stat_hospital.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.comboBox_stat_hospital.setObjectName("comboBox_stat_hospital")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/source/bar_char.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_main.addTab(self.tab, icon7, "")
        self.tab_staff_manager = QtWidgets.QWidget()
        self.tab_staff_manager.setObjectName("tab_staff_manager")
        self.btn_staff_add = QtWidgets.QPushButton(self.tab_staff_manager)
        self.btn_staff_add.setGeometry(QtCore.QRect(1096, 0, 91, 41))
        self.btn_staff_add.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.btn_staff_add.setIcon(icon3)
        self.btn_staff_add.setObjectName("btn_staff_add")
        self.tableWidget_staff = QtWidgets.QTableWidget(self.tab_staff_manager)
        self.tableWidget_staff.setGeometry(QtCore.QRect(0, 40, 1191, 671))
        self.tableWidget_staff.setStyleSheet("gridline-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 255);\n"
"background-color: rgb(245, 245, 245);")
        self.tableWidget_staff.setObjectName("tableWidget_staff")
        self.tableWidget_staff.setColumnCount(0)
        self.tableWidget_staff.setRowCount(0)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/source/group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_main.addTab(self.tab_staff_manager, icon8, "")
        self.tab_hospital_manager = QtWidgets.QWidget()
        self.tab_hospital_manager.setObjectName("tab_hospital_manager")
        self.btn_hospital_add = QtWidgets.QPushButton(self.tab_hospital_manager)
        self.btn_hospital_add.setGeometry(QtCore.QRect(1095, 0, 91, 41))
        self.btn_hospital_add.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.btn_hospital_add.setIcon(icon3)
        self.btn_hospital_add.setObjectName("btn_hospital_add")
        self.tableWidget_hospital = QtWidgets.QTableWidget(self.tab_hospital_manager)
        self.tableWidget_hospital.setGeometry(QtCore.QRect(0, 40, 1191, 671))
        self.tableWidget_hospital.setStyleSheet("gridline-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 255);\n"
"background-color: rgb(245, 245, 245);")
        self.tableWidget_hospital.setObjectName("tableWidget_hospital")
        self.tableWidget_hospital.setColumnCount(0)
        self.tableWidget_hospital.setRowCount(0)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/source/office_block.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_main.addTab(self.tab_hospital_manager, icon9, "")
        self.tab_statistics = QtWidgets.QWidget()
        self.tab_statistics.setObjectName("tab_statistics")
        self.comboBox_abnormal_age = QtWidgets.QComboBox(self.tab_statistics)
        self.comboBox_abnormal_age.setGeometry(QtCore.QRect(60, 10, 191, 35))
        self.comboBox_abnormal_age.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.comboBox_abnormal_age.setObjectName("comboBox_abnormal_age")
        self.dateEdit_abnormal_start = QtWidgets.QDateEdit(self.tab_statistics)
        self.dateEdit_abnormal_start.setGeometry(QtCore.QRect(290, 50, 161, 35))
        self.dateEdit_abnormal_start.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);\n"
"font: 20pt \"Adobe Arabic\";")
        self.dateEdit_abnormal_start.setCalendarPopup(True)
        self.dateEdit_abnormal_start.setObjectName("dateEdit_abnormal_start")
        self.label = QtWidgets.QLabel(self.tab_statistics)
        self.label.setGeometry(QtCore.QRect(460, 50, 31, 31))
        self.label.setObjectName("label")
        self.dateEdit_abnormal_end = QtWidgets.QDateEdit(self.tab_statistics)
        self.dateEdit_abnormal_end.setGeometry(QtCore.QRect(498, 50, 181, 35))
        self.dateEdit_abnormal_end.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);\n"
"font: 20pt \"Adobe Arabic\";")
        self.dateEdit_abnormal_end.setCalendarPopup(True)
        self.dateEdit_abnormal_end.setObjectName("dateEdit_abnormal_end")
        self.comboBox_abnormal_item = QtWidgets.QComboBox(self.tab_statistics)
        self.comboBox_abnormal_item.setGeometry(QtCore.QRect(250, 10, 271, 35))
        self.comboBox_abnormal_item.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.comboBox_abnormal_item.setObjectName("comboBox_abnormal_item")
        self.label_2 = QtWidgets.QLabel(self.tab_statistics)
        self.label_2.setGeometry(QtCore.QRect(780, 50, 41, 31))
        self.label_2.setObjectName("label_2")
        self.label_abnormal_count = QtWidgets.QLabel(self.tab_statistics)
        self.label_abnormal_count.setGeometry(QtCore.QRect(810, 50, 71, 31))
        self.label_abnormal_count.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_abnormal_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_abnormal_count.setObjectName("label_abnormal_count")
        self.label_4 = QtWidgets.QLabel(self.tab_statistics)
        self.label_4.setGeometry(QtCore.QRect(890, 50, 31, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.btn_abnormal_query = QtWidgets.QPushButton(self.tab_statistics)
        self.btn_abnormal_query.setGeometry(QtCore.QRect(680, 48, 91, 39))
        self.btn_abnormal_query.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.btn_abnormal_query.setIcon(icon1)
        self.btn_abnormal_query.setObjectName("btn_abnormal_query")
        self.tableWidget_abnormal = QtWidgets.QTableWidget(self.tab_statistics)
        self.tableWidget_abnormal.setGeometry(QtCore.QRect(0, 90, 1191, 621))
        self.tableWidget_abnormal.setStyleSheet("gridline-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 255);\n"
"background-color: rgb(245, 245, 245);")
        self.tableWidget_abnormal.setObjectName("tableWidget_abnormal")
        self.tableWidget_abnormal.setColumnCount(0)
        self.tableWidget_abnormal.setRowCount(0)
        self.comboBox_abnormal_right_left = QtWidgets.QComboBox(self.tab_statistics)
        self.comboBox_abnormal_right_left.setGeometry(QtCore.QRect(520, 10, 201, 35))
        self.comboBox_abnormal_right_left.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.comboBox_abnormal_right_left.setObjectName("comboBox_abnormal_right_left")
        self.comboBox_normal_abnormal_start = QtWidgets.QComboBox(self.tab_statistics)
        self.comboBox_normal_abnormal_start.setGeometry(QtCore.QRect(720, 10, 181, 35))
        self.comboBox_normal_abnormal_start.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.comboBox_normal_abnormal_start.setObjectName("comboBox_normal_abnormal_start")
        self.comboBox_abnormal_end = QtWidgets.QComboBox(self.tab_statistics)
        self.comboBox_abnormal_end.setGeometry(QtCore.QRect(940, 10, 181, 35))
        self.comboBox_abnormal_end.setStyleSheet("color: rgb(0, 0, 0);selection-color: rgb(0, 0, 255);")
        self.comboBox_abnormal_end.setObjectName("comboBox_abnormal_end")
        self.label_20 = QtWidgets.QLabel(self.tab_statistics)
        self.label_20.setGeometry(QtCore.QRect(900, 10, 31, 31))
        self.label_20.setObjectName("label_20")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/source/bar_char.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_main.addTab(self.tab_statistics, icon10, "")
        self.pushButton_setting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setting.setGeometry(QtCore.QRect(1140, 0, 41, 41))
        self.pushButton_setting.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"selection-color: rgb(46, 187, 150);\n"
"color: rgb(245, 245, 245);\n"
"border-color: rgb(245, 245, 245);")
        self.pushButton_setting.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/source/user_setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting.setIcon(icon11)
        self.pushButton_setting.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_setting.setFlat(True)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 1191, 41))
        self.label_7.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.pushButton_setting.raise_()
        self.tabWidget_main.raise_()
        self.label_user_hospital.raise_()
        self.label_user_name.raise_()
        self.label_datetime.raise_()
        self.label_user_title.raise_()
        self.label_weekday.raise_()
        main.setCentralWidget(self.centralwidget)

        self.retranslateUi(main)
        self.tabWidget_main.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "儿童眼保健检查系统"))
        self.label_user_hospital.setText(_translate("main", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_user_name.setText(_translate("main", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_datetime.setText(_translate("main", "<html><head/><body><p><span style=\" color:#ffffff;\">08:08:56 2017-11-23</span></p></body></html>"))
        self.label_user_title.setText(_translate("main", "<html><head/><body><p><br/></p></body></html>"))
        self.label_weekday.setText(_translate("main", "<html><head/><body><p><span style=\" color:#ffffff;\">星期一</span></p></body></html>"))
        self.btn_uncheck_search.setText(_translate("main", "搜索"))
        self.btn_uncheck_update.setText(_translate("main", "刷新"))
        self.labe_update_info1.setText(_translate("main", "共"))
        self.labe_update_info_count.setText(_translate("main", "1000"))
        self.labe_update_info1_3.setText(_translate("main", "位待检"))
        self.btn_appoint_new.setText(_translate("main", "新增"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_uncheck), _translate("main", "待检"))
        self.label_8.setText(_translate("main", "新生儿"))
        self.label_9.setText(_translate("main", "42天"))
        self.label_10.setText(_translate("main", "5-6月"))
        self.label_11.setText(_translate("main", "一岁"))
        self.label_12.setText(_translate("main", "二岁"))
        self.label_13.setText(_translate("main", "三岁"))
        self.label_14.setText(_translate("main", "六岁"))
        self.label_15.setText(_translate("main", "五岁"))
        self.label_16.setText(_translate("main", "四岁"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_workbench), _translate("main", "工作台"))
        self.dateEdit_end_checked.setDisplayFormat(_translate("main", "yyyy-MM-dd"))
        self.label_statistics_count_checked.setText(_translate("main", "0"))
        self.dateEdit_start_checked.setDisplayFormat(_translate("main", "yyyy-MM-dd"))
        self.label_3.setText(_translate("main", "共:"))
        self.label_5.setText(_translate("main", "位"))
        self.label_6.setText(_translate("main", "至"))
        self.btn_children_query.setText(_translate("main", "查询"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_archives), _translate("main", "已检"))
        self.label_17.setText(_translate("main", "共:"))
        self.label_18.setText(_translate("main", "位"))
        self.label_19.setText(_translate("main", "至"))
        self.btn_stat_query.setText(_translate("main", "查询"))
        self.dateEdit_stat_start.setDisplayFormat(_translate("main", "yyyy-MM-dd"))
        self.label_statistics_count.setText(_translate("main", "0"))
        self.dateEdit_stat_end.setDisplayFormat(_translate("main", "yyyy-MM-dd"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab), _translate("main", "检查统计"))
        self.btn_staff_add.setText(_translate("main", "新增"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_staff_manager), _translate("main", "人员管理"))
        self.btn_hospital_add.setText(_translate("main", "新增"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_hospital_manager), _translate("main", "医院管理"))
        self.dateEdit_abnormal_start.setDisplayFormat(_translate("main", "yyyy-MM-dd"))
        self.label.setText(_translate("main", "至"))
        self.dateEdit_abnormal_end.setDisplayFormat(_translate("main", "yyyy-MM-dd"))
        self.label_2.setText(_translate("main", "共:"))
        self.label_abnormal_count.setText(_translate("main", "0"))
        self.label_4.setText(_translate("main", "位"))
        self.btn_abnormal_query.setText(_translate("main", "查询"))
        self.label_20.setText(_translate("main", "—"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_statistics), _translate("main", "结果统计"))

from source.image import *
